### ISSUE TITLE
No script or notebook to train ddpg from scratch. 

### ISSUE THREAD

**Issue by urvishp80** [vermouth1992/CS599-Final-Project#10]
Why there is no script provided to train the dppg model just like you have provided imitation_learning.py for training imitation learning algorithm? 

It would be helpful to replicate the results and experimentations.

**Comment by vermouth1992** [comment]
Please look at this file stock_trading.py
Also, please be highly suspected of the results you got. I actually extend the project by adding some news features and found that stock market can't be predicted/acted using simple algorithms like RL or simple language model.

**Comment by urvishp80** [comment]
Thanks. I am closing the issue.

**Comment by urvishp80** [comment]
The stock_trading.py file throws an error. 

`Traceback (most recent call last):
  File "C:\Users\hp\Envs\rl-portfolio\lib\site-packages\gym\core.py", line 203, in __del__
    self.close()
  File "C:\Users\hp\Envs\rl-portfolio\lib\site-packages\gym\core.py", line 164, in close
    self.render(close=True)
  File "E:\Pirimid\drl-portfolio-management\src\environment\portfolio.py", line 298, in render
    return self._render(mode='human', close=False)
  File "E:\Pirimid\drl-portfolio-management\src\environment\portfolio.py", line 295, in _render
    self.plot()
  File "E:\Pirimid\drl-portfolio-management\src\environment\portfolio.py", line 302, in plot
    df_info = pd.DataFrame(self.infos)
AttributeError: 'PortfolioEnv' object has no attribute 'infos'`

**Comment by urvishp80** [comment]
If you guys can provide the requirement.txt for the code then also it would be really helpful. The conflict between the packages is really big issues in Python.

**Comment by vermouth1992** [comment]
Yes. I notice some non-compatible updates on openai gym environment. I will try to make a requirement tomorrow if I have time.

**Comment by urvishp80** [comment]
I solved the error by removing dtype=float32 from two lines in the PortfolioEnv. The new lines are as follows.

`self.action_space = gym.spaces.Box(0, 1, shape=(len(self.src.asset_names) + 1,))  # include cash
self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(len(abbreviation), window_length, history.shape[-1]))`

I have `gym==0.9.3` on my machine.
