### ISSUE TITLE
data_visualization does not work

### ISSUE THREAD

**Issue by szzhouyj** [vermouth1992/CS599-Final-Project#11]
Hi. Very nice work and worth a look. Actually, i think would like to play with the environment. I found that your data_visualization does not work very well. It has error saying that DataGenerator object has no attribute 'step'. it also has no attribute 'data'.

**Comment by szzhouyj** [comment]
Still many thanks for your work. I would like to add some critic. The trained models provided by you are actually not that good. Although the great profit are shown in the jupyter notebook you provide, the actually weights at given time step are not good as most of time it will put all cash in one asset （eg:[0,1,0,....,0]）. There is no meaning for portfolio managment if all weights are in asset.

**Comment by morningsky** [comment]
> Hi. Very nice work and worth a look. Actually, i think would like to play with the environment. I found that your data_visualization does not work very well. It has error saying that DataGenerator object has no attribute 'step'. it also has no attribute 'data'.

Have you solved this problem?
I solved it by run '''env.reset()''' after create env = PortfolioEnv(). or maybe you have better solution?

**Comment by szzhouyj** [comment]
> > Hi. Very nice work and worth a look. Actually, i think would like to play with the environment. I found that your data_visualization does not work very well. It has error saying that DataGenerator object has no attribute 'step'. it also has no attribute 'data'.
> 
> Have you solved this problem?
> I solved it by run '''env.reset()''' after create env = PortfolioEnv(). or maybe you have better solution?

Hi. Thank you for the
