### ISSUE TITLE
数据step错误

### ISSUE THREAD

**Issue by Jmeiying** [vermouth1992/CS599-Final-Project#15]
env = PortfolioEnv(history, abbreviation, sample_start_date='2013-08-20')
done = False
while not done:
    action = np.array([1.0] + history.shape[0] * [0.0])
    observation, reward, done, info = env.step(action)
env.render()

AttributeError: 'DataGenerator' object has no attribute 'step'

**Comment by Eloyjaws** [comment]
Works if you reset the environment immediately after creating it

```observation, info = env.reset()```
