### ISSUE TITLE
How can I train the model?

### ISSUE THREAD

**Issue by yanxurui** [vermouth1992/CS599-Final-Project#8]
Could you please tell me how can I train the model? For example, how can I get the same parameters of DDPG models used in ddpg_experiments?

Thanks!

**Comment by aimit01** [comment]
I have the same question as yanxurui - could you please tell me how to train the model, too? Many thanks!

**Comment by yanxurui** [comment]
@aimit01 
Look at #9 
I would suggest not wasting your GPU (~5 hours)
